package main

import (
	"log"

	"github.com/danilobuerger/euler/fibonacci"
)

// https://projecteuler.net/problem=2
//
// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.
func main() {
	limit := 4000000

	done := make(chan struct{})
	defer close(done)

	g := fibonacci.EvenGenerator(done)

	sum := 0
	for i := range g {
		if i > limit {
			break
		}
		sum += i
	}

	log.Println(sum)
}
